# Generated by Django 4.2 on 2023-04-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComment', models.CharField(max_length=150)),
                ('emailComment', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('dateComment', models.DateTimeField(default=django.utils.timezone.now)),
                ('publishComment', models.BooleanField(default=False)),
                ('postComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('userComment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
